name: Backend with Flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test

jobs:


  build-Backend_with_Flutter:
    name: Build Backend with Flutter
    runs-on: ubuntu-latest

    #Build Flutter
    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Build Web
        run: flutter build web --base-href /api/Notes/ -o BestNote/wwwroot/flutter_web_app

      #Build Backend with Flutter Frontend
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build .NET Application
        run: dotnet publish -c Release -o ./publish

      #Build/Publish Docker Image
      - name: Log in to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/devops_project_mda/backend-flutter:latest
