name: Flutter CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Build Web
        run: flutter build web --base-href api/Notes

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: web-release
          path: build/web
